<?php

namespace RioBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * EpreuveRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EpreuveRepository extends EntityRepository
{
    //Dernières Epreuves crées
    public function FindByLastEpreuve()
    {
       $qb = $this->createQueryBuilder('e');

       $qb->select('e.nom')
          ->addselect('e.image')
          ->addselect('e.id')
          ->orderBy('e.date', 'DESC')
          ->setMaxResults(3);


       return $qb->getQuery()->getResult();
    }
}
