<?php

namespace UserBundle\Repository;

/**
 * DatauserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DatauserRepository extends \Doctrine\ORM\EntityRepository
{
}
